/**
 * Every error code the engine sends, `<area>.<reason>`. Surfaces map each code to an i18n
 * message. A new code is an addition inside a version; removing one needs a new version.
 */
export const protocolErrorCodes = [
  "protocol.not_open",
  "protocol.bad_frame",
  "protocol.unknown_op",
  "protocol.bad_args",
  "protocol.busy",
  "protocol.too_large",
  "protocol.key_reused",
  "protocol.version",
  "auth.required",
  "auth.invalid",
  "auth.expired",
  "auth.revoked",
  "auth.origin",
  "auth.scope",
  "auth.local_only",
  "engine.starting",
  "engine.stopping",
  "engine.locked",
  "engine.timeout",
  "runtime.unavailable",
  "agent.not_found",
  "agent.archived",
  "agent.frozen",
  "agent.paper_only",
  "agent.disclaimer",
  "wallet.not_found",
  "wallet.unfunded",
  "wallet.bad_owner_key",
  "wallet.custody_down",
  "intent.not_found",
  "intent.wrong_state",
  "intent.expired",
  "intent.card_changed",
  "intent.not_yours",
  "order.not_found",
  "order.wrong_state",
  "asset.not_found",
  "asset.bad_address",
  "name.not_found",
  "name.resolver_down",
  "quote.no_route",
  "quote.venue_down",
  "chain.rpc_down",
  "chain.simulation_failed",
  "limit.needs_admin",
  "limit.over_ceiling",
  "config.invalid",
  "config.secret_inline",
  "plugin.not_found",
  "plugin.hash_mismatch",
  "plugin.review_needed",
  "job.not_found",
  "internal.error",
] as const;

/** One error code of the protocol, such as `auth.scope`. */
export type ProtocolErrorCode = (typeof protocolErrorCodes)[number];
